UI improvements
Archish007/amazon_clone_tech_task pull request #5
Opened 2024-10-11 08:25 UTC by mohitrajsinha

feat: enhance product UI with cart item count, review count, and description toggle

- Show number of items in cart on cart logo in navbar
- Display total review count next to review star widget for products
- Limit product description lines with a "See more" option for expanded view
- closes #3

2024-10-15 17:09 UTC, Archish007 commented on Aerocart/lib/utils/home_items.dart
SingleChildScrollView creates a scroll space that can cause anomalies when scrolling through overflowing text. Try to avoid using SingleChildScrollView. Instead, consider using MediaQuery to adjust the overflow by resizing the text.

2024-10-16 05:34 UTC, Archish007 requested changes
SingleChildScrollView creates a scroll space that can cause anomalies when scrolling through overflowing text. Try to avoid using SingleChildScrollView. Instead, consider using MediaQuery to adjust the overflow by resizing the text.

2024-10-19 14:03 UTC, Archish007 approved these changes

2024-10-19 14:04 UTC, merged

2024-10-23 16:42 UTC, Archish007 commented
Hey @mohitrajsinha, there’s a small issue with your commit. In the first
commit, you accidentally deleted line 25 of the screen_layout page, which
was the Provider.getData function call. This has caused problems with
fetching user details.

Please add the following statement after line 33 of the current code in the
screen_layout page as soon as possible and raise a new PR:

Provider.of<UserDetailsProvider>(context).getData();

On Wed, Oct 16, 2024 at 9:16 PM Mohit Raj Sinha ***@***.***>
wrote:

> @mohitrajsinha <https://github.com/mohitrajsinha> requested your review
> on: #5 <https://github.com/lugnitdgp/Aerocart/pull/5> UI improvements.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lugnitdgp/Aerocart/pull/5#event-14683390850>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFZD5NKOSQY3BZFC5WLJBXLZ32C5FAVCNFSM6AAAAABPYNNXSKVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJUGY4DGMZZGA4DKMA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-10-23 17:12 UTC, mohitrajsinha commented
Please add `hacktoberfest` label to this pr.
![image](https://github.com/user-attachments/assets/e86119ce-55cb-40d0-81c5-eeeea67ae944)